name: anomaly
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py313hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py313hee96239_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - pyzmq=27.1.0=py313hcf8288c_0
  - readline=8.3=hc2a1206_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py313h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.0
      - bleach==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - lightning-utilities==0.15.2
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.6.4
      - narwhals==2.5.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - pillow==11.3.0
      - plotly==6.3.0
      - prometheus-client==0.23.1
      - propcache==0.3.2
      - protobuf==6.32.1
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyparsing==3.2.5
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.39.0
      - setuptools==80.9.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.8.0
      - torch-geometric==2.6.1
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250822
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.22.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - yarl==1.20.1
prefix: /home/st4787/.conda/envs/anomaly
